### ISSUE TITLE
Interrest in SerialChiller

### ISSUE THREAD

**Issue by Wouteroosterwijk** [lasselukkari/SerialChiller#2]
Dear Lasse,

My name is Wouter Oosterwijk and i live in the Netherlands.
Your SerialChiller design really got my interrest as i am rebuilding 2 flightcases with Behringer DCX2496 inside; attached some pictures. There is no space left for adding a RS232 port in the panel and offcourse i would like to update designs to a better workable solutions without using cables. That's why i got interrested in your RS232-Wifi design, which even can run by itself (course the software is being installed to it and you can easily communite with the device by just using the IP-adres).
I would love to try this.....how can we arrange 2 of these?

Looking forward to your reply.
Kind regards,
Wouter Oosterwijk
Burg. den Hoedstraat 12
2957KA Nieuw-Lekkerland
The Netherlands
wouteroosterwijk@hotmail.com

![20200507_204457](https://user-images.githubusercontent.com/66036592/83068341-82d10200-a068-11ea-8f07-70dbfde5452d.jpg)
![20200507_204709](https://user-images.githubusercontent.com/66036592/83068363-88c6e300-a068-11ea-8d33-816117693226.jpg)
![20200516_175140](https://user-images.githubusercontent.com/66036592/83068376-8ebcc400-a068-11ea-816a-e13cec11323f.jpg)
![20200527_215244](https://user-images.githubusercontent.com/66036592/83068398-94b2a500-a068-11ea-9daf-8c224b2d188f.jpg)
![20200527_215315](https://user-images.githubusercontent.com/66036592/83068420-9a0fef80-a068-11ea-83d3-a35cbf33a415.jpg)

**Comment by lasselukkari** [comment]
Hi. I'm super busy with work at the moment. I will get back to you soon.

**Comment by Wouteroosterwijk** [comment]
Hi,

Sure...no problem, if you have a moment left, than you can always contact me.

Gr

Wouter

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________
